// Mocks generated by Mockito 5.1.0 from annotations
// in myafyahub/test/widgets_tests/shared/services/onboarding_utils_2_test.dart.
// Do not manually edit this file.

import 'package:mockito/mockito.dart' as _i1;
import 'package:myafyahub/application/core/services/datatime_parser.dart'
    as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

/// A class which mocks [DateTimeParser].
///
/// See the documentation for Mockito's code generation for more information.
class MockDateTimeParser extends _i1.Mock implements _i2.DateTimeParser {
  MockDateTimeParser() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get useCustomDateTime =>
      (super.noSuchMethod(Invocation.getter(#useCustomDateTime),
          returnValue: false) as bool);
  @override
  String parsedExpireAt(int? expiresIn) =>
      (super.noSuchMethod(Invocation.method(#parsedExpireAt, [expiresIn]),
          returnValue: '') as String);
}
